# Generated by Django 5.2.8 on 2025-11-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='quantity',
            field=models.PositiveBigIntegerField(verbose_name='Cantidad disponible'),
        ),
    ]
