# Generated by Django 5.2.8 on 2025-11-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_supply_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(verbose_name='Precio final'),
        ),
    ]
